
export const generatePriceHistory = () => {
  return Array.from({ length: 24 }, (_, i) => ({
    hour: i,
    price: 2.5 + Math.sin(i * 0.3) * 0.8 + Math.random() * 0.4
  }));
};

export const gpuRentalsData = [
  {
    id: 1,
    company: "NVIDIA",
    companyLogo: "🟢",
    model: "RTX 4090",
    tier: "High-End",
    provider: "RunPod",
    providerColor: "#6366F1",
    providerIcon: "🚀",
    currentPrice: 2.89,
    priceChange: "+12%",
    trend: "up" as const,
    vram: "24GB",
    availability: "available",
    utilization: 87,
    reliability: 95,
    priceHistory: generatePriceHistory(),
    location: "US West",
    setupTime: "2 min",
    lastRented: "5 min ago",
    performanceScore: 92,
    trustScore: 4.8
  },
  {
    id: 2,
    company: "NVIDIA", 
    companyLogo: "🟢",
    model: "A100 80GB",
    tier: "Enterprise",
    provider: "AWS EC2",
    providerColor: "#FF9900",
    providerIcon: "☁️",
    currentPrice: 4.99,
    priceChange: "-5%",
    trend: "down" as const,
    vram: "80GB",
    availability: "limited",
    utilization: 94,
    reliability: 99,
    priceHistory: generatePriceHistory(),
    location: "US East",
    setupTime: "8 min",
    lastRented: "12 min ago",
    performanceScore: 98,
    trustScore: 4.9
  },
  {
    id: 3,
    company: "NVIDIA",
    companyLogo: "🟢",
    model: "H100 80GB", 
    tier: "Enterprise",
    provider: "Google Cloud",
    providerColor: "#4285F4",
    providerIcon: "🌐",
    currentPrice: 8.99,
    priceChange: "+24%",
    trend: "up" as const,
    vram: "80GB",
    availability: "available",
    utilization: 91,
    reliability: 97,
    priceHistory: generatePriceHistory(),
    location: "EU West",
    setupTime: "5 min",
    lastRented: "3 min ago",
    performanceScore: 100,
    trustScore: 4.7
  },
  {
    id: 4,
    company: "NVIDIA",
    companyLogo: "🟢",
    model: "RTX 4080",
    tier: "High-End",
    provider: "Vast.ai",
    providerColor: "#10B981",
    providerIcon: "⚡",
    currentPrice: 1.89,
    priceChange: "+8%",
    trend: "up" as const,
    vram: "16GB",
    availability: "available",
    utilization: 76,
    reliability: 88,
    priceHistory: generatePriceHistory(),
    location: "Global",
    setupTime: "1 min",
    lastRented: "8 min ago",
    performanceScore: 85,
    trustScore: 4.3
  },
  {
    id: 5,
    company: "NVIDIA",
    companyLogo: "🟢",
    model: "RTX 3090",
    tier: "Mid-Range",
    provider: "Paperspace",
    providerColor: "#8B5CF6",
    providerIcon: "📄",
    currentPrice: 1.69,
    priceChange: "-3%",
    trend: "down" as const,
    vram: "24GB",
    availability: "available", 
    utilization: 68,
    reliability: 92,
    priceHistory: generatePriceHistory(),
    location: "US East",
    setupTime: "30 sec",
    lastRented: "15 min ago",
    performanceScore: 78,
    trustScore: 4.5
  },
  {
    id: 6,
    company: "NVIDIA",
    companyLogo: "🟢",
    model: "V100 32GB",
    tier: "Professional",
    provider: "Lambda Labs",
    providerColor: "#F59E0B",
    providerIcon: "λ",
    currentPrice: 2.49,
    priceChange: "+15%",
    trend: "up" as const,
    vram: "32GB",
    availability: "limited",
    utilization: 82,
    reliability: 94,
    priceHistory: generatePriceHistory(),
    location: "US West",
    setupTime: "2 min",
    lastRented: "7 min ago",
    performanceScore: 88,
    trustScore: 4.6
  }
];
