// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnntolixtwhufgexdouq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdubnRvbGl4dHdodWZnZXhkb3VxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjU4ODAsImV4cCI6MjA2NTUwMTg4MH0.3BUQdC2A8OWleV0NlXHr8mMpANd9nTmdoTDY3snNpO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);